# Generated by Django 4.2.2 on 2023-06-15 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0002_customuser_is_active_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childcategory",
            name="main_category",
        ),
        migrations.RemoveField(
            model_name="classifieds",
            name="Country",
        ),
        migrations.RemoveField(
            model_name="classifieds",
            name="category",
        ),
        migrations.DeleteModel(
            name="ClassifiedsTypes",
        ),
        migrations.RemoveField(
            model_name="classifiedsutils",
            name="main_classifieds",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="ChildCategory",
        ),
        migrations.DeleteModel(
            name="Classifieds",
        ),
        migrations.DeleteModel(
            name="ClassifiedsUtils",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
